### ISSUE TITLE
Keep seed constant when seed set to -1/random in A1111

### ISSUE THREAD

**Issue by wogam** [Jibaku789/percentage-grid-sd-webui-script#1]
Hi, thanks for making this script - it's so useful for LoRA test. Please could we have a way to keep the seed the same when using the seed -1, especially when doing multiple batches as it makes comparing results much easier.

Currently if you set it to -1 and you have 5 percentages, they will all use a different seed - when they should use the same one - giving incomparable results.

Thank you.

**Comment by jonatalamantes** [comment]
I will add a new seed button with the behavior (fixed, random)
Also i will move this repository to my other account
https://github.com/Jibaku789/percentage-grid-sd-webui-script

**Comment by Jibaku789** [comment]
Done, will be moved to this repository
https://github.com/Jibaku789/percentage-grid-sdwebui-script
